name: fitoagricola
description: A new Flutter project.

version: 1.2.6+27

environment:
  sdk: '^2.18.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  intl: 0.19.0
  phosphor_flutter: ^2.0.0
  dotted_line: ^3.2.2
  grouped_list: ^5.1.2
  logger: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  dotted_border: ^2.1.0
  riverpod_annotation: ^2.3.5
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  file_picker: ^8.0.0+1
  flutter_dotenv: ^5.1.0
  dropdown_search: ^5.0.6
  # estados_municipios: ^2.0.2
  google_maps_flutter: ^2.6.0
  label_marker: ^1.0.1
  fl_chart: ^0.67.0
  webview_flutter: ^4.7.0
  brasil_fields: ^1.14.1
  photo_view: ^0.15.0
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.7
  path_provider: ^2.1.3
  device_info_plus: ^10.1.0
  image_picker: ^1.1.0
  workmanager: ^0.5.2
  expandable_datatable: ^0.0.7
  flutter_staggered_grid_view: ^0.7.0
  flutter_osm_plugin: ^0.70.4
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^12.0.0
  flutter_isolate: ^2.0.5-pre
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^17.1.1
  provider: ^6.1.2
  wakelock: ^0.4.0
  html_unescape: ^2.0.0
  youtube_player_flutter: ^9.0.1
  flutter_inappwebview: ^6.0.0
  flutter_map_tile_caching: ^9.1.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  image_gallery_saver: ^2.0.3
  photo_manager: ^3.1.1
  flutter_map_location_marker: ^9.0.0
  http_parser: ^4.0.2
  open_filex: ^4.4.0
  carousel_slider: ^4.2.1
  like_button: ^2.0.5
  sqflite: ^2.3.3+1
  flutter_background_service: ^5.0.7
  flutter_background_service_ios: ^5.0.2
  flutter_background_service_android: ^6.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/json/locations.json
    - assets/images/
    - assets/images/map_markers/
    - assets/images/content_images/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterRegular.ttf
          weight: 400

flutter_icons:
  image_path: 'assets/app/app-icon.png'
  adaptive_icon_background: '#064E43'
  adaptive_icon_foreground: 'assets/app/app-icon.png'
  android: true
  ios: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/app/splash.png'
  android_12:
    color: '#ffffff'
    image: 'assets/app/splash.png'
